mysql:
  host: 127.0.0.1
  port: 3306
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  db: gvb_db
  user: root
  password: root
  log_level: dev
logger:
  level: info
  prefix: '[gvb]'
  director: "true"
  show-line: true
  log-in-console: true
system:
  host: 0.0.0.0
  port: 8080
  env: release
upload:
  size: 2
  path: uploads/file
site_info:
  created_at: ""
  name: ""
  title: ""
  version: 1.0.2
  job: ""
  addr: ""
qq:
  app_id: xx
  key: xx
  redirect: http://xx.xx.com/login?flag==qq
qi_niu:
  enable: false
  access_key: ""
  secret_key: ""
  bucket: ""
  cdn: ""
  zone: ""
  prefix: ""
  size: 0
email:
  host: smtp.qq.com
  port: 465
  user: 123@qq.com
  password: xxx
  default_from_email: Arevn
  use_ssl: false
  user_tls: false
jwt:
  secret: xxx
  expires: 48
  issuer: xx
